---
TEST_SECTION_1:
  A: 1
  B: 1e-1
  C: 1e1
TEST_SECTION_2:
  A: 2
  B: 2e-2
  C: 2e2
TEST_SECTION_3:
  A: 3
  B: 3e-3
  C: 3e3
TEST_SECTION_4:
  A: 4
  B: 4e-4
  C: 4e4
TEST_SECTION_5:
  A: 5
  B: 5e-5
  C: 5e5
TEST_SECTION_6:
  A: 6
  B: 6e-6
  C: 6e6
TEST_SECTION_7:
  A: 7
  B: 7e-7
  C: 7e7
TEST_SECTION_8:
  A: 8
  B: 8e-8
  C: 8e8
