---
name: Methyl ads des
args: 20 20 5 0.01
data:
  reactions/ADS_METHYL_TO_111/A:
    range: 1.2e8..1.2e10
    step: 2
    type: exp
  reactions/ADS_METHYL_TO_DIMER/A:
    range: 1e12..1e14
    step: 2
    type: exp
  reactions/DES_METHYL_FROM_111/A:
    range: 5.4e12..5.4e14
    step: 2
    type: exp
  reactions/DES_METHYL_FROM_BRIDGE/A:
    range: 1.7e13..1.7e15
    step: 2
    type: exp
  reactions/DES_METHYL_FROM_DIMER/A:
    range: 5.3e11..5.3e13
    step: 2
    type: exp
  reactions/DIMER_DROP/A:
    range: 0.8e2..0.8e4
    step: 2
    type: exp
  reactions/DIMER_DROP/Ea:
    range: 2.2e2..2.2e4
    step: 2
    type: exp
  reactions/DIMER_DROP_AT_END/A:
    range: 2.2e2..2.2e4
    step: 2
    type: exp
  reactions/DIMER_DROP_AT_END/Ea:
    range: 1e2..1e4
    step: 2
    type: exp
  reactions/DIMER_DROP_IN_MIDDLE/A:
    range: 2.2e2..2.2e4
    step: 2
    type: exp
  reactions/DIMER_DROP_IN_MIDDLE/Ea:
    range: 1.2e2..1.2e4
    step: 2
    type: exp
  reactions/DIMER_DROP_NEAR_BRIDGE/A:
    range: 1.2e7..1.2e9
    step: 2
    type: exp
  reactions/DIMER_DROP_NEAR_BRIDGE/Ea:
    range: 4e2..4e4
    step: 2
    type: exp
  reactions/DIMER_FORMATION/A:
    range: 8.9e7..8.9e9
    step: 2
    type: exp
  reactions/DIMER_FORMATION/Ea:
    range: 0.8e2..0.8e4
    step: 2
    type: exp
  reactions/DIMER_FORMATION_AT_END/A:
    range: 8.9e7..8.9e9
    step: 2
    type: exp
  reactions/DIMER_FORMATION_AT_END/Ea:
    range: 0.4e2..0.4e4
    step: 2
    type: exp
  reactions/DIMER_FORMATION_IN_MIDDLE/A:
    range: 8.9e7..8.9e9
    step: 2
    type: exp
  reactions/DIMER_FORMATION_NEAR_BRIDGE/A:
    range: 7.5e7..7.5e9
    step: 2
    type: exp
  reactions/DIMER_FORMATION_NEAR_BRIDGE/Ea:
    range: 4e2..4e4
    step: 2
    type: exp
  reactions/METHYL_ON_DIMER_HYDROGEN_MIGRATION/A:
    range: 2.1e11..2.1e13
    step: 2
    type: exp
  reactions/METHYL_ON_DIMER_HYDROGEN_MIGRATION/Ea:
    range: 37.5e2..37.5e4
    step: 2
    type: exp
  reactions/METHYL_TO_HIGH_BRIDGE/A:
    range: 9.8e8..9.8e10
    step: 2
    type: exp
  reactions/METHYL_TO_HIGH_BRIDGE/Ea:
    range: 15.3e2..15.3e4
    step: 2
    type: exp
  reactions/MIGRATION_THROUGH_DIMERS_ROW/A:
    range: 2.4e7..2.4e9
    step: 2
    type: exp
  reactions/MIGRATION_THROUGH_DIMERS_ROW/Ea:
    range: 16e2..16e4
    step: 2
    type: exp
