---
name: Dimer reactions
args: 5 5 0.5 0.01 xyz
data:
  env/concentrations/H:
    range: 1e-12..1e-8
    step: 1
    type: exp
    and:
      env/concentrations/CH3:
        range: 1e-12..1e-8
        step: 1
        type: exp