---
name: Methyl ads des
args: 20 20 5 0.01
data:
  reactions/ADS_METHYL_TO_111/A:
    range: 1.2e8..1.2e10
    step: 2
    type: exp
  reactions/ADS_METHYL_TO_DIMER/A:
    range: 1e12..1e14
    step: 2
    type: exp
  reactions/DES_METHYL_FROM_111/A:
    range: 5.4e12..5.4e14
    step: 2
    type: exp
  reactions/DES_METHYL_FROM_BRIDGE/A:
    range: 1.7e13..1.7e15
    step: 2
    type: exp
  reactions/DES_METHYL_FROM_DIMER/A:
    range: 5.3e11..5.3e13
    step: 2
    type: exp
