---
name: test sequence
args: 10 10 20 0.1 xyz
data:
  p/S1/A:
    range: 1..10
    step: 2
    type: line
  p/S2/B:
    range: 10..1
    step: -2
    type: line
  p/S3/C:
    range: 1e1..1e9
    step: 8
    type: exp
  p/S4/A:
    range: 1e9..1e1
    step: -8
    type: exp
  p/S5/B:
    values: 43 98
